### PR TITLE
test

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@raedrizqie can you test the msxml2 and msxml6 libraries? mingw-w64-headers-git and mingw-w64-crt-git have to be compiled with the 'msxml' branch from here.

**Comment by raedrizqie** [comment]
thanks for your help! will let you know soon..

**Comment by raedrizqie** [comment]
im not very familiar in compiling mingw crt.. maybe you could provide me the libs? kinda busy with chromium right now..

**Comment by Biswa96** [comment]
Which msystem do you want the packages for?

**Comment by raedrizqie** [comment]
clang

**Comment by Biswa96** [comment]
I have added the clang64 packages here https://github.com/Biswa96/mingw-w64/releases/tag/test. Use `pacman -U <path>` command to install those. It will show as a downgrade in pacman because I have use a shallow cloned repository. But that will not cause any issue.

Not all GUIDs are exported in libmsxml2 or libmsxml6 compared to Windows SDK counterpart. I can try to add those missing one also.

**Comment by raedrizqie** [comment]
Nice! Thank you very much for this.. I dont need to install the full package.. just need to test libmsxml2.a only..

Will update to you later.. Thanks again :)

**Comment by raedrizqie** [comment]
Good news.. both msxml2 & msxml6 linked without problems.. thank you!

**Comment by Biswa96** [comment]
BTW, it'd also help if you test entire headers and crt packages. This change imports various headers from wine. I can not recall can project to test the headers also.

Another point. Can you provide which project or which source code or which build files mentioned/need those libraries? I add the project name in git commit message just to keep track of things. For example, like this https://github.com/mingw-w64/mingw-w64/commit/1092e5bf9c06ca157b3826bc05bb3dbc3a7f841c

**Comment by raedrizqie** [comment]
> BTW, it'd also help if you test entire headers and crt packages. This change imports various headers from wine. I can not recall can project to test the headers also.

ok, will do

> 
> Another point. Can you provide which project or which source code or which build files mentioned/need those libraries? I add the project name in git commit message just to keep track of things. For example, like this [mingw-w64@1092e5b](https://github.com/mingw-w64/mingw-w64/commit/1092e5bf9c06ca157b3826bc05bb3dbc3a7f841c)

actually, im doing this to try to add support for pythonwin extensions in pywin32 package.. they require mfc lib

but, then again.. even if we could compile, and got no runtime error, it is still illegal to redistribute mfc dll anyway :(

**Comment by Biswa96** [comment]
I do not see any msxml requirement in pywin32 project

```
$ grep -ir msxml /f/pywin32/
/f/pywin32/com/win32comext/axscript/client/framework.py:        # We should still work with an existing site (or so MSXML believes :)
```

**Comment by raedrizqie** [comment]
msxml is needed for atl/mfc library..

**Comment by Biswa96** [comment]
🛎️ did you check the mingw headers and crt packages?

**Comment by raedrizqie** [comment]
Ah.. sorry..I forgot about that.. libloaderapi.h conflicts with some other headers.. winnt.h for example..

**Comment by Biswa96** [comment]
Can you share the error message? It may not related to this change. I just pinged to upstream the msxml change in mingw-w64.

**Comment by raedrizqie** [comment]
This time I installed the headers correctly, and there were no error.. :)

**Comment by Biswa96** [comment]
Thanks for testing. Also thanks for the chromium/angle/v8 works. If you need anything to upstream in those project (except chromium, its huge) I can try to help.

**Comment by Biswa96** [comment]
What kind of secondary storage do you use?

**Comment by raedrizqie** [comment]
I didnt use any secondary storage.. hmm.. maybe thats why my 1st attempt to clone it, failed.. if it fails this 2nd time.. goodbye to chromium I guess :{

**Comment by Biswa96** [comment]
I mean which storage medium do you use? ssd or nmve or optane ?

**Comment by raedrizqie** [comment]
Ah.. this is an old lappy.. running win8.1.. ssd maybe

**Comment by Biswa96** [comment]
First one sent https://sourceforge.net/p/mingw-w64/mailman/message/37754078/

**Comment by raedrizqie** [comment]
Q: Does angleproject buildable on aarch64?

**Comment by Biswa96** [comment]
I have not tried it, will explore that later.

**Comment by Biswa96** [comment]
First one applied here https://github.com/mingw-w64/mingw-w64/commit/9470b4247d0ed2750c1aa23c40fe593152ad2e37

Second one sent here https://sourceforge.net/p/mingw-w64/mailman/message/37754336/

**Comment by Biswa96** [comment]
I shall delete this repository after second one is merged. Shall we discuss things in msys2 discord?

**Comment by raedrizqie** [comment]
Ok.. no problem

**Comment by Biswa96** [comment]
> Q: Does angleproject buildable on aarch64?

It seems that cross compile is possible with gn. But for that I would like to change things in angle pkgbuild a little bit. For example,
1. set is_mingw true by default
2. set is_clang from pkgbuild by checking $MSYSTEM
3. use ANGLE_PLATFORM_WINDOWS instead of _WIN32 & upstream gcc style arch defs also.
etc.

**Comment by raedrizqie** [comment]
> > Q: Does angleproject buildable on aarch64?
> 
> It seems that cross compile is possible with gn. But for that I would like to change things in angle pkgbuild a little bit. For example,
> 
> 1. set is_mingw true by default

meaning, setting it in PKGBUILD?

> 2. set is_clang from pkgbuild by checking $MSYSTEM

ok

> 3. use ANGLE_PLATFORM_WINDOWS instead of _WIN32 & upstream gcc style arch defs also.
>    etc.

ok

**Comment by Biswa96** [comment]
> meaning, setting it in PKGBUILD?

Jus thinking. Just set is_mingw true in gn file, like is_win.

**Comment by raedrizqie** [comment]
Like setting it in BUILDCONFIG.gn ?

**Comment by Biswa96** [comment]
Yeah, in build/config/BUILDCONFIG.gn. I shall create a PR with the changes and let you know.

**Comment by Biswa96** [comment]
Second patch was added in this commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/0a35c2a22425dd5ed2fd99e442480f43821548dc/

Now you can update the commit in mingw-packages/mingw-w64-headers-git and mingw-w64-crt-git to get the latest changes. No other steps are required.

Bye bye this repository 👋

**Comment by raedrizqie** [comment]
Thanks for your time!

**Pull request closed without merging**
